# Generated by Django 5.1.3 on 2024-11-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_type', models.CharField(choices=[('Food - Wheat', 'Food - Wheat'), ('Food - Nuts', 'Food - Nuts'), ('Food - Dairy', 'Food - Dairy'), ('Food - Seafood', 'Food - Seafood'), ('Environmental - Pollen', 'Environmental - Pollen'), ('Environmental - Dust', 'Environmental - Dust'), ('Environmental - Mold', 'Environmental - Mold'), ('Environmental - Insect', 'Environmental - Insect'), ('Food - Spices', 'Food - Spices')], max_length=50)),
                ('ige_levels', models.FloatField()),
                ('exposure_frequency', models.CharField(choices=[('Rarely', 'Rarely'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Seasonal', 'Seasonal')], max_length=20)),
                ('symptoms', models.CharField(max_length=50)),
                ('family_history', models.CharField(max_length=3)),
                ('reaction_severity', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElectrolyteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_sodium', models.FloatField()),
                ('serum_potassium', models.FloatField()),
                ('serum_calcium', models.FloatField()),
                ('serum_magnesium', models.FloatField()),
                ('bicarbonate', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('outcome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
